import {
  HiOutlinePuzzle,
  HiOutlineCollection,
  HiOutlineClipboardList,
  HiOutlineClipboardCheck,
  HiOutlineDocumentDuplicate,
  HiOutlineUserGroup,
  HiUserGroup,
  HiOutlineTicket,
  HiClock,
  HiDocument,
  HiBadgeCheck,
  HiMail,
  HiOutlineDocument,
  HiClipboard,
  HiDocumentText,
  HiCalendar,
  HiDocumentDuplicate,
  HiClipboardList,
  HiPuzzle,
  HiCollection,
  HiClipboardCheck,
} from 'react-icons/hi';
import { Card } from '../../types/allowed-modules.type';

// Declare selection
export const Modules: Array<Card> = [
  {
    icon: <HiPuzzle className="w-10 h-6 text-orange-800" />,
    color: 'orange',
    title: 'Position Duties, Responsibilities, & Competencies',
    description: 'Select and set per position',
    destination: 'dnr',
    linkType: 'router',
    state: true,
  },
  {
    icon: <HiCollection className="w-6 h-6 text-indigo-500" />,
    color: 'indigo',
    title: 'Position Request',
    description: 'Request for new positions',
    destination: 'prf',
    linkType: 'router',
    state: true,
  },
  {
    icon: <HiClipboardList className="w-10 h-6 text-green-600" />,
    color: 'lime',
    title: 'Applicant Endorsement',
    description: 'Select from a list of endorsed applicants for shortlisting',
    destination: 'endorsement',
    linkType: 'router',
    state: true,
  },
  {
    icon: <HiClipboardCheck className="w-10 h-6 text-green-600" />,
    color: 'green',
    title: 'Appointing Authority Selection',
    description: 'Applicant Selection',
    destination: 'selection',
    linkType: 'router',
    state: true,
  },

  {
    icon: <HiUserGroup className="w-6 h-6 text-indigo-600" />,
    color: 'indigo',
    title: 'Personnel Selection Board',
    description: 'Applicant interview',
    destination: 'psb',
    linkType: 'href',
    state: true,
  },
  {
    icon: <HiBadgeCheck className="w-6 h-6 text-blue-600" />,
    color: 'blue',
    title: 'Approvals',
    description: 'Approve Leaves/Pass Slips',
    destination: 'approvals',
    linkType: 'router',
    state: true,
  },
  {
    icon: <HiDocumentDuplicate className="w-6 h-6 text-orange-600" />,
    color: 'orange',
    title: 'Personal Data Sheet',
    description: 'Update your PDS record',
    destination: 'pds',
    linkType: 'router',
    state: true,
  },

  {
    icon: <HiClock className="w-6 h-6 text-rose-600" />,
    color: 'rose',
    title: 'DTR',
    description: 'Daily Time Record',
    destination: 'dtr',
    linkType: 'router',
    state: true,
  },
  {
    icon: <HiDocumentText className="w-6 h-6 text-green-600" />,
    color: 'green',
    title: 'Pass Slip',
    description: 'Apply for Pass Slip',
    destination: 'pass-slip',
    linkType: 'router',
    state: true,
  },

  {
    icon: <HiCalendar className="w-6 h-6 text-blue-600" />,
    color: 'blue',
    title: 'Leaves',
    description: 'Apply or view Leave Credits',
    destination: 'leaves',
    linkType: 'router',
    state: true,
  },

  {
    icon: <HiMail className="w-6 h-6 text-indigo-700" />,
    color: 'indigo',
    title: 'Email',
    description: 'Check your Emails',
    destination: 'email',
    linkType: 'href',
    state: true,
  },
];
