import {
  HiOutlinePuzzle,
  HiOutlineCollection,
  HiOutlineClipboardList,
  HiOutlineClipboardCheck,
  HiOutlineDocumentDuplicate,
  HiOutlineUserGroup,
  HiUserGroup,
  HiOutlineTicket,
  HiClock,
  HiDocument,
  HiBadgeCheck,
} from 'react-icons/hi';
import { Card } from '../../types/allowed-modules.type';

// Declare selection
export const Modules: Array<Card> = [
  {
    icon: <HiOutlinePuzzle className="w-6 h-6 text-orange-800" />,
    color: 'orange',
    title: 'Position Duties, Responsibilities, & Competencies',
    description: 'Select and set per position',
    destination: 'dnr',
    linkType: 'router',
    state: true,
  },
  {
    icon: <HiOutlineCollection className="w-6 h-6 text-indigo-400" />,
    color: 'indigo',
    title: 'Position Request',
    description: 'Request for new positions',
    destination: 'prf',
    linkType: 'href',
    state: true,
  },
  {
    icon: <HiOutlineClipboardList className="w-6 h-6 text-gray-600" />,
    color: 'gray',
    title: 'Applicant Endorsement',
    description: 'Select from a list of endorsed applicants for shortlisting',
    destination: 'endorsement',
    linkType: 'router',
    state: true,
  },
  {
    icon: <HiOutlineClipboardCheck className="w-6 h-6 text-green-600" />,
    color: 'green',
    title: 'Appointing Authority Selection',
    description: 'Applicant Selection',
    destination: 'selection',
    linkType: 'router',
    state: true,
  },
  {
    icon: <HiOutlineDocumentDuplicate className="w-6 h-6 text-rose-600" />,
    color: 'rose',
    title: 'Personal Data Sheet',
    description: 'Update your PDS record',
    destination: 'pds',
    linkType: 'router',
    state: true,
  },
  {
    icon: <HiUserGroup className="w-6 h-6 text-indigo-600" />,
    color: 'indigo',
    title: 'Personnel Selection Board',
    description: 'Applicant interview',
    destination: 'psb',
    linkType: 'href',
    state: true,
  },
  {
    icon: <HiOutlineTicket className="w-6 h-6 text-blue-600" />,
    color: 'blue',
    title: 'Leaves',
    description: 'Apply or view leave credits',
    destination: 'leaves',
    linkType: 'router',
    state: true,
  },
  {
    icon: <HiClock className="w-6 h-6 text-rose-600" />,
    color: 'rose',
    title: 'DTR',
    description: 'Daily Time Record',
    destination: 'dtr',
    linkType: 'router',
    state: true,
  },

  {
    icon: <HiDocument className="w-6 h-6 text-green-600" />,
    color: 'green',
    title: 'Pass Slip',
    description: 'Apply for Pass Slip',
    destination: 'pass-slip',
    linkType: 'router',
    state: true,
  },
  {
    icon: <HiBadgeCheck className="w-6 h-6 text-blue-600" />,
    color: 'blue',
    title: 'Approvals',
    description: 'Approve Leaves/Pass Slips',
    destination: 'approvals',
    linkType: 'router',
    state: true,
  },
];
